### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [washburnad/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by washburnad** [comment]
Just added the meta tags.  I added them directly to application.html.erb.  I did a google search to see if there was a more ruby-like way to add them but didn't find one.

git and heroku are both updated.

**Comment by MarcoMorawec** [comment]
@washburnad  :+1: 

Or how a typical web dev would respond:

![](http://replygif.net/i/457.gif)

FYI: Make sure you're closing the issue, since you're done with it :)
